"""add_is_admin_is_approved

Revision ID: 722c8d0de117
Revises: c4d52402c580
Create Date: 2026-06-14 15:46:03.009578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '722c8d0de117'
down_revision: Union[str, None] = 'c4d52402c580'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Добавляем колонки с временным дефолтом для старых записей
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('users', sa.Column('is_approved', sa.Boolean(), nullable=False, server_default=sa.text('true')))

    # Сразу убираем server_default, чтобы он не висел на уровне самой СУБД
    op.alter_column('users', 'is_admin', server_default=None)
    op.alter_column('users', 'is_approved', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_approved')
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
