"""add_tasks_table

Revision ID: d5a3e1e2cd26
Revises: d4e5f6a7b8c9
Create Date: 2026-06-14 02:19:53.830368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from src.tasks.models import Task


# revision identifiers, used by Alembic.
revision: str = 'd5a3e1e2cd26'
down_revision: Union[str, None] = 'd4e5f6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('course_number', sa.Integer(), nullable=True),
    sa.Column('group_name', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('file_paths', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_group_name'), 'tasks', ['group_name'], unique=False)
    op.create_index(op.f('ix_tasks_teacher_id'), 'tasks', ['teacher_id'], unique=False)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('users', 'patronymic',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'is_academic_data_frozen')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_academic_data_frozen', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('avatar_url', sa.VARCHAR(length=1024), server_default=sa.text("'/static/default_avatar.svg'::character varying"), autoincrement=False, nullable=False))
    op.alter_column('users', 'patronymic',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)
    op.alter_column('users', 'first_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)
    op.drop_index(op.f('ix_tasks_teacher_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_group_name'), table_name='tasks')
    op.drop_table('tasks')
    # ### end Alembic commands ###
